### ISSUE TITLE
Problem contacting RubyGem owner

### ISSUE THREAD

**Issue by inventionlabsSydney** [inventionlabsSydney/capistrano-sneakers#15]
Primarily for @Tensho and others who might be interested.

I tried reaching out to Daniel the owner of the capistrano-sneakers rubygem and have been bounced.

Attached is a copy of the bounce transcript:
<img width="808" alt="screen shot 2018-01-27 at 00 11 13" src="https://user-images.githubusercontent.com/2543079/35441196-addc4188-02f6-11e8-99d8-9ad6c460acf0.png">

Any suggestions on how we might be able to secure the rubygem for ourselves?

Suggestions plz.

--Karl.

**Comment by Tensho** [comment]
Daniel will reach you out by himself ^_^

Andrew Babichev

**Comment by inventionlabsSydney** [comment]
What's the latest with this @Tensho ?

**Comment by Tensho** [comment]
Seems like nothing :(
@dvandersluis, could you transfer an ownership at rubygems to @inventionlabsSydney?
https://github.com/dvandersluis/compendium/issues/14

**Comment by dvandersluis** [comment]
Again I'm not sure how this gem ended up in my ownership because I have nothing to do with the project.

@inventionlabsSydney what is the email address on rubygems?

**Comment by inventionlabsSydney** [comment]
@dvandersluis my email is k@rl.ag :) We're not sure how it happened but that's what happened ha.

**Comment by dvandersluis** [comment]
I've transfered ownership to k@rl.ag.

**Comment by Tensho** [comment]
@dvandersluis thank you 🙇

**Comment by inventionlabsSydney** [comment]
I can confirm this has now been transferred, thank you @dvandersluis!

Tensho, shall we setup some CI/CD for this?

**Comment by inventionlabsSydney** [comment]
@Tensho I have released and published to rubygems. Closing.

**Comment by Tensho** [comment]
Arigato 🙇
