### ISSUE TITLE
sneakers:start not working

### ISSUE THREAD

**Issue by palpandiR** [inventionlabsSydney/capistrano-sneakers#23]
When i call sneakers start ( cap staging sneakers:start) that process not complete.. it show the logs but not complete.

 too many same workers are created  in server but not reviving the  messages from Queue.
My configuration are 
set :sneakers_default_hooks => true
set :sneakers_pid => File.join(shared_path, 'tmp', 'pids', 'sneakers.pid') # ensure this path exists in production before deploying
set :sneakers_env => fetch(:rack_env, fetch(:rails_env, fetch(:stage)))
set :sneakers_log => File.join(shared_path, 'log', 'sneakers.log')
set :sneakers_roles => :app
set :sneakers_processes => 1
set :sneakers_workers, false
set :sneakers_run_config, true
set :sneakers_workers, ['QuotesWorker']

 ps aux | grep sneakers
deploy   15130  0.0  0.0  11232  2920 ?        Ss   12:09   0:00 bash -c cd /home/deploy/staging/XXX/current && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.2.2" RAILS_ENV="staging" WORKERS="QuotesWorker" ; $HOME/.rbenv/bin/rbenv exec bundle exec rake sneakers:run )
deploy   15131  0.0  0.0  11236  2004 ?        S    12:09   0:00 bash -c cd /home/deploy/staging/XXX/current && ( export RBENV_ROOT="$HOME/.rbenv" RBENV_VERSION="2.2.2" RAILS_ENV="staging" WORKERS="QuotesWorker" ; $HOME/.rbenv/bin/rbenv exec bundle exec rake sneakers:run )
deploy   15132  7.8  4.6 987520 189272 ?       Sl   12:09   0:05 /home/deploy/.rbenv/versions/2.2.2/bin/rake sneakers:run
deploy   15171  0.0  4.4 993688 180288 ?       Sl   12:09   0:00 /home/deploy/.rbenv/versions/2.2.2/bin/rake sneakers:run
deploy   15183  0.0  4.4 993688 180288 ?       Sl   12:09   0:00 /home/deploy/.rbenv/versions/2.2.2/bin/rake sneakers:run
deploy   15188  0.0  4.4 993688 179900 ?       Sl   12:09   0:00 /home/deploy/.rbenv/versions/2.2.2/bin/rake sneakers:run
deploy   15207  0.0  4.4 993688 180092 ?       Sl   12:09   0:00 /home/deploy/.rbenv/versions/2.2.2/bin/rake sneakers:run
deploy   15229  0.0  0.0  12944   984 pts/2    R+   12:10   0:00 grep --color=auto sneakers

**Comment by inventionlabsSydney** [comment]
Hi, What does your sneakers log say?

**Comment by inventionlabsSydney** [comment]
Closing due to lack of communication.
